export const POST_CODE = {
  NOT_FOUND: 'POST_NOT_FOUND',
  ALREADY_EXIST: 'POST_ALREADY_EXIST',
};
export const COMMENT_CODE = {
  NOT_FOUND: 'COMMENT_NOT_FOUND',
  ALREADY_EXIST: 'COMMENT_ALREADY_EXIST',
};
export const USER_CODE = {
  NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_EXIST: 'USER_ALREADY_EXIST',
  EMAIL_ALREADY_EXIST: 'USER_EMAIL_ALREADY_',
};
