export const COMPANY_CODE = {
  NOT_FOUND: 'COMPANY_NOT_FOUND',
  ALREADY_EXIST: 'COMPANY_ALREADY_EXIST',
  INVALID_LEGALNAME_FORMAT: 'INVALID_LEGALNAME_FORMAT',
};
export const POST_CODE = {
  NOT_FOUND: 'POST_NOT_FOUND',
  ALREADY_EXIST: 'POST_ALREADY_EXIST',
};
export const FILE_CODE = {
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXIST: 'ALREADY_EXIST',
  REQUIRED: 'REQUIRED',
};
export const FILE_TYPE_CODE = {
  NOT_SUPPORTED: 'NOT_SUPPORTED',
};
export const POST_IMAGE_CODE = {
  NOT_FOUND: 'POST_IMAGE_NOT_FOUND',
  ALREADY_EXIST: 'POST_IMAGE_ALREADY_EXIST',
};
export const COMMENT_CODE = {
  NOT_FOUND: 'COMMENT_NOT_FOUND',
  ALREADY_EXIST: 'COMMENT_ALREADY_EXIST',
};
export const USER_CODE = {
  NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_EXIST: 'USER_ALREADY_EXIST',
  EMAIL_ALREADY_EXIST: 'USER_EMAIL_ALREADY_',
  FULLNAME_REQUIRED: 'FULLNAME_REQUIRED',
};
export const REACTION_CODE = {
  NOT_FOUND: 'REACTION_NOT_FOUND',
};
