export const post = [
  { text: 'Release Buttock Subcu/Fascia, Extern Approach' },
  { text: 'Supplement Bi Sperm Cord with Nonaut Sub, Open Approach' },
  { text: 'Fusion Occip Jt w Nonaut Sub, Post Appr A Col, Perc' },
  { text: 'Extraction of Left Pleura, Percutaneous Endoscopic Approach' },
  { text: 'Dilation of Middle Esophagus, Endo' },
  { text: 'Revision of Intbd Fus Dev in C-thor Jt, Perc Approach' },
  { text: 'Revision of Autol Sub in Vas Deferens, Perc Approach' },
  { text: 'Drainage of L Com Iliac Art, Perc Endo Approach, Diagn' },
  { text: 'Removal of Intbd Fus Dev from Cerv Jt, Open Approach' },
  { text: 'Introduction of Other Gas into Eye, Via Opening' },
  { text: 'Bypass L Hepatic Duct to Stomach w Intralum Dev, Open' },
  { text: 'Supplement R Ankle Bursa/Lig with Synth Sub, Open Approach' },
  { text: 'Bypass Up Esophag to Ileum with Synth Sub, Open Approach' },
  { text: 'Ultrasonography of Ophthalmic Arteries, Intravascular' },
  { text: 'Contact Radiation of Pelvic Bones' },
  { text: 'Plaque Radiation of Hard Palate' },
  { text: 'Revision of Int Fix in L Finger Phalanx, Perc Approach' },
  { text: 'Extraction of Left Cornea, External Approach' },
  { text: 'Bypass L Popl Art to Poplit Art w Autol Art, Open' },
  { text: 'Revision of Drain Dev in Trunk Subcu/Fascia, Extern Approach' },
  { text: 'Release Cecum, Via Natural or Artificial Opening Endoscopic' },
  { text: 'Dilation of Face Artery with 3 Intralum Dev, Open Approach' },
  { text: 'Removal of Nonaut Sub from R Up Extrem, Extern Approach' },
  { text: 'Reposition Left Tarsal Joint, Perc Endo Approach' },
  { text: 'Repair Lumbosacral Plexus, Open Approach' },
  { text: 'Resection of Left Main Bronchus, Open Approach' },
  { text: 'Plain Radiography of Right Kidney using Low Osmolar Contrast' },
  { text: 'Insertion of Infusion Device into R Knee, Perc Approach' },
  { text: 'Removal of Other Device from Upper Back, Perc Approach' },
  { text: 'HDR Brachytherapy of Chest Wall using Californium 252' },
  { text: 'Fluoroscopy of Splenic Arteries' },
  { text: 'Reposition L Humeral Head with Ext Fix, Perc Endo Approach' },
  { text: 'Release Bilateral Fallopian Tubes, Endo' },
  { text: 'Repair Right Humeral Head, External Approach' },
  { text: 'Bypass Left Subclavian Artery to L Up Leg Art, Open Approach' },
  { text: 'Resection of Hymen, Via Natural or Artificial Opening' },
  { text: 'Removal of Drain Dev from R Low Extrem, Extern Approach' },
  { text: 'Fragmentation in Right Ureter, External Approach' },
  { text: 'Drainage of R Axilla Lymph with Drain Dev, Open Approach' },
  { text: 'Supplement Pulmonary Valve with Nonaut Sub, Perc Approach' },
  { text: 'Dilation of Right Basilic Vein, Perc Endo Approach' },
  { text: 'Excision of Left Hip Tendon, Open Approach' },
  { text: 'Supplement Left Clavicle with Nonaut Sub, Open Approach' },
  { text: 'Bypass L Verteb Vein to Up Vein w Nonaut Sub, Perc Endo' },
  { text: 'Plain Radiography of Left Hand/Finger Joint' },
  { text: 'Revision of Intraluminal Device in Upper Vein, Open Approach' },
  { text: 'Nuclear Medicine, Veins, Planar Nuclear Medicine Imaging' },
  { text: 'Restriction of L Low Lobe Bronc with Intralum Dev, Endo' },
  { text: 'Release Hymen, Open Approach' },
  { text: 'Supplement Cerebral Meninges with Nonaut Sub, Perc Approach' },
  { text: 'Dilate R Axilla Art, Bifurc, w Intralum Dev, Perc' },
  { text: 'Dilate Face Art, Bifurc, w Intralum Dev, Perc Endo' },
  { text: 'Bypass L Atrium to Pulm Trunk with Nonaut Sub, Open Approach' },
  { text: 'Revision of Drain Dev in R Extraoc Muscle, Perc Approach' },
  { text: 'Reposition Left Metacarpal, External Approach' },
  { text: 'Dilation of R Int Mamm Art, Bifurc, Perc Approach' },
  { text: 'Excision of R Metacarpophal Jt, Perc Endo Approach, Diagn' },
  { text: 'Drainage of L Abd Tendon with Drain Dev, Perc Endo Approach' },
  { text: 'Extirpation of Matter from Head & Neck Tendon, Open Approach' },
  { text: 'Dilation of Coronary Artery, Two Arteries, Perc Approach' },
  { text: 'Drainage of Left Buttock, Open Approach, Diagnostic' },
  { text: 'Supplement Lg Intest with Nonaut Sub, Perc Endo Approach' },
  { text: 'Supplement Right Mandible with Nonaut Sub, Open Approach' },
  { text: 'Revision of Drainage Device in Upper Artery, Perc Approach' },
  { text: 'Exercise Treatment of Integu Low Back/LE using Prosthesis' },
  { text: 'Alteration of Right Upper Eyelid, Percutaneous Approach' },
  { text: 'Planar Nucl Med Imag of Veins using Oth Radionuclide' },
  { text: 'Supplement L Low Extrem with Nonaut Sub, Perc Endo Approach' },
  { text: 'Dilate 3 Cor Art, Bifurc, w Radioact Intralum, Open' },
  { text: 'Dilation of L Renal Art with 4 Drug-elut, Perc Approach' },
  { text: 'Destruction of Left Wrist Joint, Percutaneous Approach' },
  { text: 'Restrict Thor Aorta Asc w Fenestr Dev 3+, Open' },
  { text: 'Assist Device Fit using Orthosis' },
  { text: 'Monitoring of Intracranial Pressure, Percutaneous Approach' },
  { text: 'Bypass R Ext Iliac Art to R Ext Ilia, Perc Endo Approach' },
  { text: 'Resection of Uterine Supporting Structure, Open Approach' },
  { text: 'Excision of Left Ureter, Percutaneous Endoscopic Approach' },
  { text: 'Replacement of Sup Vena Cava with Nonaut Sub, Open Approach' },
  { text: 'Speech/Lang Screen Assessment using AV Equipment' },
  { text: 'Fluoroscopy of L Low Extrem Art using Oth Contrast' },
  { text: 'Reattachment of Rectum, Percutaneous Endoscopic Approach' },
  { text: 'Assistive Listening System/Device Selection Assessment' },
  { text: 'Receptive/Expressive Language Treatment' },
  { text: 'Bypass R Subclav Art to R Extracran Art, Open Approach' },
  { text: 'Insertion of Intralum Dev into L Ventricle, Perc Approach' },
  { text: 'Bypass R Com Iliac Art to B Com Ilia w Autol Vn, Perc Endo' },
  { text: 'Control Bleeding in Right Pleural Cavity, Perc Endo Approach' },
  { text: 'Dilate Hepatic Art, Bifurc, w 3 Intralum Dev, Perc Endo' },
  { text: 'Supplement Sup Mesent Vein with Nonaut Sub, Open Approach' },
  { text: 'Reposition R Up Extrem Bursa/Lig, Open Approach' },
  { text: 'Release R Low Extrem Bursa/Lig, Extern Approach' },
  { text: 'Beam Radiation of Cervix using Heavy Particles' },
  { text: 'Therapeutic Exercise Treatment of Musculosk Up Back/UE' },
  { text: 'Measure Peripheral Nervous Electr Activity, Extern' },
  { text: 'Drainage of Lower Vein, Percutaneous Endoscopic Approach' },
  { text: 'Transfer Right Upper Leg Tendon, Perc Endo Approach' },
  { text: 'Extirpate matter from L Com Iliac Art, Bifurc, Perc' },
  { text: 'Extirpation of Matter from Pericardium, Open Approach' },
  { text: 'Dilate Sup Mesent Art, Bifurc, w 3 Intralum Dev, Perc' },
  { text: 'Excision of Right Thorax Tendon, Perc Approach, Diagn' },
  { text: 'Revision of Nonaut Sub in R Finger Phalanx, Extern Approach' },
  { text: 'Supplement Male Perineum with Nonaut Sub, Perc Endo Approach' },
  { text: 'Excision of Right Popliteal Artery, Perc Approach, Diagn' },
  { text: 'Compression of Chest Wall using Intermittent Pressure Device' },
  { text: 'Drainage of Inf Mesent Vein, Perc Endo Approach, Diagn' },
  { text: 'Restriction of Left Parotid Duct, Open Approach' },
  { text: 'Drainage of Bilateral Lungs, Endo, Diagn' },
  { text: 'Destruction of Cul-de-sac, Percutaneous Approach' },
  { text: 'Insertion of Spacer into R Shoulder Jt, Perc Endo Approach' },
  { text: 'Revision of Synth Sub in L Humeral Shaft, Extern Approach' },
  { text: 'CT Scan of Ear using L Osm Contrast, Unenh, Enhance' },
  { text: 'Supplement R Finger Phalanx Jt w Autol Sub, Perc Endo' },
  { text: 'Transfusion of Nonaut WBC into Periph Art, Perc Approach' },
  { text: 'Excision of Thymus, Open Approach' },
  { text: 'Reposition Right Ulnar Artery, Open Approach' },
  { text: 'Drainage of Left Carpal Joint, Perc Endo Approach, Diagn' },
  { text: 'Supplement L Epididymis with Nonaut Sub, Perc Endo Approach' },
  { text: 'Supplement Abdominal Wall with Synth Sub, Perc Endo Approach' },
  { text: 'Repair Right Adrenal Gland, Open Approach' },
  { text: 'Alteration of Right Upper Leg, Perc Endo Approach' },
  { text: 'Insertion of Infusion Device into Neck, Perc Endo Approach' },
  { text: 'Fusion Thor Jt w Intbd Fus Dev, Post Appr P Col, Open' },
  { text: 'Replace Neck Skin w Synth Sub, Full Thick, Extern' },
  { text: 'Revision of Spacer in R Metacarpocarp Jt, Extern Approach' },
  { text: 'Extirpation of Matter from Right Middle Ear, Open Approach' },
  { text: 'Excision of Mediastinum, Percutaneous Endoscopic Approach' },
  { text: 'ROM & Jt Mobility Trmt Integu Up Back/UE w Oth Equip' },
  { text: 'Dilation of Upper Artery with 2 Intralum Dev, Perc Approach' },
  { text: 'Bypass Right Ventricle to Aorta, Perc Endo Approach' },
  { text: 'Removal of Infusion Device from Kidney, Endo' },
  { text: 'Supplement Right Lacrimal Duct with Autol Sub, Endo' },
  { text: 'Drainage of Left Lacrimal Duct with Drainage Device, Endo' },
  { text: 'Abortion of Products of Conception, Laminaria, Via Opening' },
  { text: 'Resection of Bilateral Vas Deferens, Perc Endo Approach' },
  { text: 'Drainage of L Abd Bursa/Lig with Drain Dev, Open Approach' },
  { text: 'Change Other Device on Right Upper Extremity' },
  { text: 'Occlusion of L Verteb Art with Extralum Dev, Perc Approach' },
  { text: 'Supplement R Popl Art with Autol Sub, Perc Endo Approach' },
  { text: 'Repair Right Hip Bursa and Ligament, Open Approach' },
  { text: 'Insertion of Other Device into R Low Arm, Perc Approach' },
  { text: 'Revision of Intraluminal Device in Nose, Open Approach' },
  { text: 'Extirpation of Matter from Appendix, Percutaneous Approach' },
  { text: 'Supplement L Up Extrem with Autol Sub, Open Approach' },
  { text: 'Supplement Right Kidney Pelvis with Synth Sub, Via Opening' },
  { text: 'Drainage of Epiglottis, Percutaneous Endoscopic Approach' },
  { text: 'Resection of Right Finger Phalanx, Open Approach' },
  { text: 'Bypass Pancreat Duct to Duoden w Intralum Dev, Open' },
  { text: 'Bypass Pancreat Duct to Duoden w Intralum Dev, Open' },
  { text: 'Dilation of Esophageal Vein with Intralum Dev, Perc Approach' },
  { text: 'Repair Rectum, Percutaneous Approach' },
  { text: 'Revision of Spacer in R Toe Phalanx Jt, Perc Endo Approach' },
  { text: 'Transfer Perineum Subcu/Fascia w Skin, Subcu, Fascia, Open' },
  { text: 'Replace R Up Leg Subcu/Fascia w Autol Sub, Perc' },
  { text: 'Destruction of Int Mamm, R Lymph, Perc Approach' },
  { text: 'Supplement R Shoulder with Autol Sub, Open Approach' },
  { text: 'Drainage of Left Shoulder Muscle, Perc Endo Approach' },
  { text: 'Transfer L Trunk Muscle with Skin, Subcu, Perc Endo Approach' },
  { text: 'Bypass L Brach Art to L Up Arm Art w Synth Sub, Open' },
  { text: 'Drainage of R Ant Tib Art with Drain Dev, Open Approach' },
  { text: 'Revision of Infusion Device in Lum Disc, Open Approach' },
  { text: 'Inspection of Left Acromioclavicular Joint, Perc Approach' },
  { text: 'Restriction of Left Common Iliac Vein, Open Approach' },
  { text: 'Bypass Bilateral Ureters to Cutaneous, Open Approach' },
  { text: 'Revision of Drainage Device in Pericard Cav, Open Approach' },
  { text: 'Supplement R Thorax Tendon w Nonaut Sub, Perc Endo' },
  { text: 'Replacement of Azygos Vein with Nonaut Sub, Open Approach' },
  { text: 'Insertion of Pedcl Stabl Dev into T-lum Jt, Open Approach' },
  { text: 'Extirpate matter from L Renal Art, Bifurc, Perc Endo' },
  { text: 'Insert Int Fix in L Metacarpophal Jt, Perc Endo' },
  { text: 'Occlusion of Right Colic Artery, Percutaneous Approach' },
  { text: 'Drain L Inf Parathyroid w Drain Dev, Perc Endo' },
  { text: 'Lower Arteries, Dilation' },
  { text: 'Transfer Facial Nerve to Accessory Nerve, Perc Endo Approach' },
  { text: 'Removal of Autol Sub from T-lum Disc, Perc Endo Approach' },
  { text: 'Gastrointestinal System, Occlusion' },
  { text: 'Occlusion of Hemiazygos Vein, Open Approach' },
  { text: 'Auditory Processing Assessment using Other Equipment' },
  { text: 'Supplement R Ankle Bursa/Lig w Nonaut Sub, Perc Endo' },
  { text: 'Drainage of Left Toe Phalangeal Joint, Perc Endo Approach' },
  { text: 'Revision of Infusion Device in Right Lung, Perc Approach' },
  { text: 'Drainage of Right Colic Artery with Drain Dev, Open Approach' },
  { text: 'Release Perineum Bursa and Ligament, Percutaneous Approach' },
  { text: 'HDR Brachytherapy of Peripheral Nerve using Palladium 103' },
  { text: 'Division of Right Thorax Bursa and Ligament, Perc Approach' },
  { text: 'Replace of L Foot Tendon with Synth Sub, Perc Endo Approach' },
  { text: 'Occlusion of Up Esophag with Intralum Dev, Perc Approach' },
  { text: 'Dilation of Gastric Artery, Open Approach' },
  { text: 'Supplement L Up Leg Muscle with Synth Sub, Open Approach' },
  { text: 'Fluoroscopy of Bilateral Jugular Veins, Guidance' },
  { text: 'Removal of Nonaut Sub from Bladder, Open Approach' },
  { text: 'Drain L Wrist Bursa/Lig w Drain Dev, Perc Endo' },
  { text: 'Occlusion of Abdominal Aorta, Open Approach' },
  { text: 'Bypass Cranial Cav to L Pleural Cav w Synth Sub, Open' },
  { text: 'Bypass R Com Iliac Art to R Int Ilia, Perc Endo Approach' },
  { text: 'Drainage of Right Superior Parathyroid Gland, Perc Approach' },
  { text: 'Destruction of Left Atrium, Open Approach' },
  { text: 'Repair Left Foot Tendon, Percutaneous Approach' },
  { text: 'Removal of Infusion Dev from Up Intest Tract, Open Approach' },
  { text: 'Dilate 2 Cor Art, Bifurc, w 2 Intralum Dev, Perc' },
  { text: 'Excision of Ileocecal Valve, Perc Endo Approach, Diagn' },
  { text: 'Dilation of Left External Iliac Artery, Perc Endo Approach' },
  { text: 'Bypass L Ventricle to L Pulm Art w Synth Sub, Perc Endo' },
  { text: 'Removal of Int Fix from R Tarsal, Perc Endo Approach' },
  { text: 'Exercise Trmt Musculosk Head, Neck w Mech/Electromech Equip' },
  { text: 'Alteration of Bi Ext Ear with Synth Sub, Extern Approach' },
  { text: 'Ultrasonography of Bilateral Common Carotid Arteries' },
  { text: 'Drainage of R Wrist Bursa/Lig with Drain Dev, Open Approach' },
  { text: 'Drainage of Int Mamm, R Lymph with Drain Dev, Perc Approach' },
  { text: 'Supplement R Pulm Vein with Autol Sub, Perc Endo Approach' },
  { text: 'Replacement of L Foot Skin with Synth Sub, Extern Approach' },
  { text: 'Dilate R Axilla Art, Bifurc, w 4 Drug-elut, Perc' },
  { text: 'Fusion of R Toe Phalanx Jt with Ext Fix, Perc Endo Approach' },
  { text: 'Reposition Right Internal Jugular Vein, Perc Approach' },
  { text: 'Alteration of Left Breast with Autol Sub, Perc Approach' },
  { text: 'Inspection of Larynx, Percutaneous Endoscopic Approach' },
  { text: 'Group Counseling for Substance Abuse Treatment, Spiritual' },
  { text: 'Occlusion of Urethra with Intraluminal Device, Via Opening' },
  { text: 'Reposition Right Temporal Artery, Perc Endo Approach' },
  { text: 'Extirpate of Matter from L Foot Subcu/Fascia, Open Approach' },
  { text: 'Dilate L Fem Art, Bifurc, w Drug-elut Intra, Open' },
  { text: 'Bypass R Ext Iliac Art to L Ext Ilia w Nonaut Sub, Perc Endo' },
  { text: 'Occlusion L Up Extrem Lymph w Intralum Dev, Open' },
  { text: 'Bypass R Kidney Pelvis to Bladder w Nonaut Sub, Open' },
  { text: 'Removal of Nonaut Sub from Coccygeal Jt, Perc Approach' },
  { text: 'Excision of Right Glenoid Cavity, Perc Endo Approach' },
  { text: 'Insertion of Int Fix into Lum Vertebra, Perc Endo Approach' },
  { text: 'Release Chordae Tendineae, Open Approach' },
  { text: 'Excision of Left Foot Skin, External Approach, Diagnostic' },
  { text: 'Dilate L Peroneal Art, Bifurc, w 2 Drug-elut, Open' },
  { text: 'Supplement R Low Extrem Bursa/Lig w Nonaut Sub, Open' },
  { text: 'Bypass Up Esophag to Duoden w Synth Sub, Perc Endo' },
  { text: 'Excision of Left Upper Lobe Bronchus, Via Opening' },
  { text: 'Bypass 2 Cor Art from Aorta with Autol Art, Open Approach' },
  { text: 'Bypass Bi Ureter to R Ureter w Nonaut Sub, Perc Endo' },
  { text: 'Extraction of Perineum Skin, External Approach' },
  { text: 'Insertion of Infusion Device into Esophagus, Perc Approach' },
  { text: 'Dilation of Left External Carotid Artery, Perc Endo Approach' },
  { text: 'Repair Right Metacarpal, External Approach' },
  { text: 'Removal of Other Device from Pericard Cav, Open Approach' },
  { text: 'Occlusion L Pulm Vein w Extralum Dev, Perc Endo' },
  { text: 'Fusion >7 T Jt w Synth Sub, Post Appr P Col, Open' },
  { text: 'Revision of Int Fix in R Finger Phalanx, Extern Approach' },
  { text: 'Resection of Left Mastoid Sinus, Open Approach' },
  { text: 'Excision of Left Posterior Tibial Artery, Perc Endo Approach' },
  { text: 'Excision of Lumbosacral Plexus, Open Approach, Diagnostic' },
  { text: 'Supplement Lumbar Vertebra with Nonaut Sub, Open Approach' },
  { text: 'Repair Left Lower Lobe Bronchus, Via Opening' },
  { text: 'Reposition Left Fibula with Hybrid Ext Fix, Perc Approach' },
  { text: 'CT Scan Bi Renal Vein w L Osm Contrast, Unenh, Enhance' },
  { text: 'Removal of Monitoring Device from Ureter, Via Opening' },
  { text: 'Revision of Synth Sub in L Acetabulum, Perc Approach' },
  { text: 'Drainage of Left Hypogastric Vein, Open Approach, Diagnostic' },
  { text: 'Replacement of Left Kidney Pelvis with Synth Sub, Endo' },
  { text: 'Resection of Bilateral Fallopian Tubes, Endo' },
  { text: 'Revision of Nonaut Sub in R Tarsal, Extern Approach' },
  { text: 'Excision of Left Humeral Shaft, Perc Endo Approach' },
  { text: 'Drainage of Right Ulna with Drainage Device, Perc Approach' },
  { text: 'Repair Ileum, Percutaneous Endoscopic Approach' },
  { text: 'Division of Cervical Vertebra, Open Approach' },
  { text: 'Extirpation of Matter from Left Tarsal Joint, Open Approach' },
  { text: 'Reposition Upper Tooth, All, Open Approach' },
  { text: 'Reattachment of Right Hand Tendon, Perc Endo Approach' },
  { text: 'Dilation of Middle Colic Artery, Percutaneous Approach' },
  { text: 'Removal of Drain Dev from Tracheobronc Tree, Perc Approach' },
  { text: 'Excision of Ascending Colon, Via Opening, Diagn' },
  { text: 'Repair Perineum Subcu/Fascia, Open Approach' },
  { text: 'Removal of Autol Sub from Up Vein, Open Approach' },
  { text: 'Release Right Common Iliac Artery, Perc Endo Approach' },
  { text: 'Removal of Infusion Device from Kidney, Endo' },
  { text: 'Insertion of Facet Stabl Dev into Occip Jt, Perc Approach' },
  { text: 'Exercise Treatment of Resp Low Back/LE using Prosthesis' },
  { text: 'Extirpation of Matter from R Glenoid Cav, Perc Approach' },
  { text: 'Bypass Gallbladder to Cystic Duct, Perc Endo Approach' },
  { text: 'Bypass Abd Aorta to R Int Ilia with Autol Vn, Open Approach' },
  { text: 'Excision of Papillary Muscle, Perc Endo Approach, Diagn' },
  { text: 'Bypass L Ext Iliac Art to R Ext Ilia w Nonaut Sub, Open' },
  { text: 'Replacement of R Hypogast Vein with Autol Sub, Open Approach' },
  { text: 'Excision of Head and Neck Tendon, Perc Endo Approach' },
  { text: 'Revision of Drainage Device in R Low Extrem, Open Approach' },
  { text: 'Dilate R Axilla Art, Bifurc, w 3 Intralum Dev, Perc' },
  { text: 'Destruction of L Low Arm & Wrist Tendon, Open Approach' },
  { text: 'Fusion Cerv Jt w Synth Sub, Post Appr P Col, Perc Endo' },
  { text: 'Bypass R Axilla Art to Bi Up Leg Art w Autol Art, Open' },
  { text: 'Bypass Right Ureter to Bladder with Synth Sub, Open Approach' },
  { text: 'Drainage of Lumbar Vertebral Joint, Open Approach' },
  { text: 'Supplement R Low Arm Subcu/Fascia w Synth Sub, Open' },
  { text: 'Beam Radiation of Femur using Photons >10 MeV' },
  { text: 'Extirpation of Matter from Chordae Tendineae, Open Approach' },
  { text: 'Release Sternum, Percutaneous Endoscopic Approach' },
  { text: 'Destruction of Int Mamm, R Lymph, Open Approach' },
  { text: 'Removal of Radioact Elem from Pelvic Cav, Perc Endo Approach' },
  { text: 'Excision of Right Breast, Percutaneous Approach, Diagnostic' },
  { text: 'Drainage of Middle Esophagus, Percutaneous Approach, Diagn' },
  { text: 'Replace of L Frontal Bone with Synth Sub, Perc Endo Approach' },
  { text: 'Restriction of Left Temporal Artery, Percutaneous Approach' },
  { text: 'Replace L Low Leg Skin w Synth Sub, Full Thick, Extern' },
  { text: 'Alteration of Right Upper Eyelid, External Approach' },
  { text: 'Oral Peripheral Mechanism Assessment using Other Equipment' },
  { text: 'Occlusion of Thorax Lymphatic, Perc Endo Approach' },
  { text: 'Reposition Left Radius, Percutaneous Endoscopic Approach' },
  { text: 'Insertion of Facet Stabl Dev into Lum Jt, Perc Endo Approach' },
  { text: 'Excision of Right Lower Extremity, Perc Endo Approach, Diagn' },
  { text: 'Control Bleeding in Right Foot, Percutaneous Approach' },
  { text: 'Extirpation of Matter from Left Rib, Perc Endo Approach' },
  { text: 'Communicative/Cognitive Integration Skills Assessment' },
  { text: 'Drainage of Right Middle Lung Lobe, Endo, Diagn' },
  { text: 'Revision of Infusion Device in R Ankle Jt, Open Approach' },
  { text: 'Occlusion R Com Iliac Art w Intralum Dev, Perc' },
  { text: 'Drainage of Right Temporomandibular Joint, Open Approach' },
  { text: 'Drainage of Left Carpal with Drainage Device, Open Approach' },
  { text: 'Removal of Autol Sub from Kidney, Via Opening' },
  { text: 'Supplement Aortic Valve with Synth Sub, Perc Approach' },
  { text: 'Excision of Thor Aorta Asc, Open Approach, Diagn' },
  { text: 'Removal of Splint on Left Upper Arm' },
  { text: 'Measurement of Venous Saturation, Peripheral, Perc Approach' },
  { text: 'Drainage of Right Kidney, Via Natural or Artificial Opening' },
  { text: 'Revision of Autol Sub in Hair, Extern Approach' },
  { text: 'Reposition Left Tibia with Intramed Fix, Perc Endo Approach' },
  { text: 'Dilation of R Ant Tib Art with Intralum Dev, Open Approach' },
  { text: 'Motor Functn Treatment of Integu Head, Neck using Oth Equip' },
  { text: 'Bypass L Com Iliac Art to Low Ex Art w Synth Sub, Perc Endo' },
  { text: 'Extirpation of Matter from Bilateral Breast, Open Approach' },
  { text: 'Reposition L Abd Bursa/Lig, Perc Endo Approach' },
  { text: 'Revision of Synth Sub in L Wrist Jt, Perc Approach' },
  { text: 'Bypass R Ureter to Colon with Synth Sub, Perc Endo Approach' },
  { text: 'Beam Radiation of Hard Palate using Photons 1 - 10 MeV' },
  { text: 'Reposition Right Lower Eyelid, Open Approach' },
  { text: 'Removal of Drainage Device from Right Lung, Extern Approach' },
  { text: 'Extirpation of Matter from L Thorax Bursa/Lig, Open Approach' },
  { text: 'Insertion of Infusion Device into L Up Extrem, Perc Approach' },
  { text: 'Dilate L Ant Tib Art, Bifurc, w Intralum Dev, Open' },
  { text: 'Introduction of Monoclonal Antibody into POC, Via Opening' },
  { text: 'Removal of Autol Sub from R Metatarsal, Perc Approach' },
  { text: 'Replace L Kidney Pelvis w Synth Sub, Perc Endo' },
  { text: 'Supplement Bladder Neck with Autol Sub, Via Opening' },
  { text: 'Resection of Left Humeral Shaft, Open Approach' },
  { text: 'Transfer Right Hip Tendon, Percutaneous Endoscopic Approach' },
  { text: 'Replacement of Left Cornea with Nonaut Sub, Perc Approach' },
  { text: 'Destruction of Left Ovary, Percutaneous Endoscopic Approach' },
  { text: 'Bypass Pulm Trunk from Innom Art w No Dev, Perc Endo' },
  { text: 'Dilate R Subclav Art, Bifurc, w 2 Intralum Dev, Perc Endo' },
  { text: 'Excision of L Acromioclav Jt, Perc Endo Approach, Diagn' },
  { text: 'Transfer Chest Subcu/Fascia w Skin, Subcu, Fascia, Open' },
  { text: 'Revision of Stimulator Lead in Bladder, Endo' },
  { text: 'Fusion 2-6 C Jt w Intbd Fus Dev, Ant Appr A Col, Perc Endo' },
  { text: 'Replace of R Up Femur with Nonaut Sub, Perc Endo Approach' },
  { text: 'Replacement of Left Eye with Synth Sub, Open Approach' },
  { text: 'Transfuse Nonaut Red Blood Cells in POC, Circ, Perc' },
  { text: 'Low Dose Rate (LDR) Brachytherapy of Nose using Iridium 192' },
  { text: 'Extirpate matter from L Metacarpophal Jt, Perc Endo' },
  { text: 'Drainage of Lumbar Nerve, Open Approach, Diagnostic' },
  { text: 'Laser Interstitial Thermal Therapy of Pineal Body' },
  { text: 'Occlusion of L Main Bronc with Intralum Dev, Perc Approach' },
  { text: 'Occlusion of Right Face Vein, Percutaneous Approach' },
  { text: 'Bypass Periton Cav to Cutan w Synth Sub, Perc Endo' },
  { text: 'Destruction of Right Middle Lobe Bronchus, Endo' },
  { text: 'Revision of Nonaut Sub in R Eye, Open Approach' },
  { text: 'Release Bilateral Fallopian Tubes, Open Approach' },
  { text: 'Dilation of R Fem Art with Drug-elut Intra, Open Approach' },
  { text: 'Dilate L Foot Art w 4+ Intralum Dev, Perc Endo' },
  { text: 'Extirpation of Matter from Nasal Turbinate, Perc Approach' },
  { text: 'Replacement of R Fibula with Synth Sub, Perc Endo Approach' },
  { text: 'Excision of Chordae Tendineae, Percutaneous Approach, Diagn' },
  { text: 'Excision of Duodenum, Open Approach' },
  { text: 'Destruction of L Low Extrem Bursa/Lig, Perc Endo Approach' },
  { text: 'Fusion of Right Tarsal Joint with Ext Fix, Perc Approach' },
  { text: 'Reposition Coronary Artery, One Artery, Open Approach' },
  { text: 'Drainage of Right Radial Artery, Perc Endo Approach, Diagn' },
  { text: 'Transfer Pudendal Nerve to Perineal Nerve, Open Approach' },
  { text: 'Bypass L Subclav Art to L Pulm Art w Synth Sub, Open' },
  { text: 'Repair Bilateral Epididymis, Perc Endo Approach' },
  { text: 'Repair Bilateral Femoral Region, Percutaneous Approach' },
  { text: 'Removal of Synth Sub from Pelvic Cav, Perc Endo Approach' },
  { text: 'Excision of Right Upper Leg Skin, External Approach, Diagn' },
  { text: 'Insertion of Int Fix into Occip Jt, Open Approach' },
  { text: 'Excision of Left Tunica Vaginalis, Percutaneous Approach' },
  { text: 'Supplement Cecum with Nonaut Sub, Perc Endo Approach' },
  { text: 'Supplement Right Scapula with Synth Sub, Perc Endo Approach' },
  { text: 'Release Left Metatarsal-Phalangeal Joint, Open Approach' },
  { text: 'Excision of Right Cornea, External Approach, Diagnostic' },
  { text: 'Replacement of R Up Leg Tendon with Synth Sub, Open Approach' },
  { text: 'Drainage of Prepuce, Percutaneous Approach, Diagnostic' },
  { text: 'Dilation of Left Peroneal Artery, Bifurcation, Perc Approach' },
  { text: 'Fusion of R Toe Phalanx Jt with Ext Fix, Perc Approach' },
  { text: 'Restriction of Asc Colon with Extralum Dev, Perc Approach' },
  { text: 'Beam Radiation of Neck Skin using Neutrons' },
  { text: 'Replace Aort Valve w Zoopl Rapid Depl, Perc, New Tech 2' },
  { text: 'Division of Right Knee Tendon, Perc Endo Approach' },
  { text: 'Revision of Autol Sub in R Carpal, Perc Approach' },
  { text: 'Repair Right Acromioclavicular Joint, Percutaneous Approach' },
  { text: 'Removal of Drain Dev from Cisterna Chyli, Perc Endo Approach' },
  { text: 'Destruction of Right Lung, Via Natural or Artificial Opening' },
  { text: 'Repair Left Tympanic Membrane, Via Opening' },
  { text: 'Introduction of Local Anesthetic into Lower GI, Endo' },
  { text: 'Insertion of Radioact Elem into L Knee, Perc Endo Approach' },
  { text: 'Restriction of R Great Saphenous, Perc Endo Approach' },
  { text: 'Introduce Oth Antineoplastic in Periph Vein, Perc' },
  { text: 'Transplantation of Musculoskel Sys into POC, Perc Approach' },
  { text: 'Supplement Upper Vein with Nonaut Sub, Open Approach' },
  { text: 'Dilation of Left Lower Lobe Bronchus, Perc Endo Approach' },
  { text: 'Ultrasonography of Left Knee' },
  { text: 'Replacement of Skull with Autol Sub, Open Approach' },
  { text: 'Insert Radioact Elem in Tracheobronc Tree, Perc' },
  { text: 'Reposition Left Shoulder Joint, Percutaneous Approach' },
  { text: 'Detachment at Left 4th Toe, Complete, Open Approach' },
  { text: 'Reposition Left Hip Muscle, Percutaneous Endoscopic Approach' },
  { text: 'Revision of Autol Sub in Uterus & Cervix, Extern Approach' },
  { text: 'Excision of Right Radial Artery, Perc Approach, Diagn' },
  { text: 'Bypass L Ext Iliac Art to R Femor A w Nonaut Sub, Perc Endo' },
  { text: 'Occlusion of R Ulnar Art with Extralum Dev, Open Approach' },
  { text: 'Replace of L Brach Art with Autol Sub, Perc Endo Approach' },
  { text: 'Occlusion of R Ulnar Art with Extralum Dev, Open Approach' },
  { text: 'Fluoroscopy R Low Extrem Art w Oth Contrast, Laser Intraop' },
  { text: 'Introduction of Oth Therap Subst into Joint, Perc Approach' },
  { text: 'Restriction of Esophagus with Intraluminal Device, Endo' },
  { text: 'Transplantation of Heart, Syngeneic, Open Approach' },
  { text: 'Excision of R Com Carotid, Open Approach, Diagn' },
  { text: 'Drainage of Brachial Plexus, Open Approach, Diagnostic' },
  { text: 'Transfer Head Muscle with Skin, Subcu, Open Approach' },
  { text: 'Measurement of Arterial Sound, Peripheral, Open Approach' },
  { text: 'Reposition Right Lower Leg Muscle, Perc Endo Approach' },
  { text: 'Dilate R Com Iliac Art w 4 Drug-elut, Perc Endo' },
  { text: 'Release Right Axillary Lymphatic, Open Approach' },
  { text: 'Supplement R Shoulder Bursa/Lig w Synth Sub, Open' },
  { text: 'Restrict R Com Iliac Vein w Extralum Dev, Perc' },
  { text: 'Inspection of Cranial Cavity, Perc Endo Approach' },
  { text: 'Bypass Left Fallopian Tube to R Fallop, Open Approach' },
  { text: 'Revision of Ext Fix in L Humeral Shaft, Perc Approach' },
  { text: 'Excision of Hymen, Open Approach' },
  { text: 'Occlusion of Right Posterior Tibial Artery, Open Approach' },
  { text: 'CT Scan of L Hip using H Osm Contrast' },
  { text: 'Revision of Monitoring Device in Stomach, Perc Endo Approach' },
  { text: 'Drainage of L Low Lobe Bronc with Drain Dev, Open Approach' },
  { text: 'Revision of Synthetic Substitute in Small Intestine, Endo' },
  { text: 'Alteration of Left Breast with Nonaut Sub, Open Approach' },
  { text: 'Transfer Tongue, Open Approach' },
  { text: 'Excision of Left Upper Arm Muscle, Perc Approach, Diagn' },
  { text: 'Release Right Trunk Tendon, External Approach' },
  { text: 'Drainage of Vagina with Drainage Device, Open Approach' },
  { text: 'Fusion of Right Elbow Joint with Int Fix, Perc Approach' },
  { text: 'Repair Cystic Duct, Via Natural or Artificial Opening' },
  { text: 'Removal of Synth Sub from Cerv Disc, Perc Endo Approach' },
  { text: 'Drainage of Left Ovary with Drain Dev, Perc Endo Approach' },
  { text: 'Beam Radiation of Brain Stem using Photons <1 MeV' },
  { text: 'Introduction of Anti-inflammatory into Lower GI, Endo' },
  { text: 'Revision of Autol Sub in Low Bursa/Lig, Perc Approach' },
  { text: 'Supplement L Seminal Vesicle with Synth Sub, Open Approach' },
  { text: 'Introduction of Other Anti-infective into POC, Via Opening' },
  { text: 'Dilation of Cystic Duct with Intralum Dev, Open Approach' },
  { text: 'Coord/Dexterity Trmt Musculosk Head, Neck w Prosthesis' },
  { text: 'Beam Radiation of Chest Wall using Photons 1 - 10 MeV' },
  { text: 'Bypass L Subclav Art to R Low Arm Art, Open Approach' },
  { text: 'Drainage of Radial Nerve with Drainage Device, Open Approach' },
  { text: 'Dilate L Ext Iliac Art, Bifurc, w 2 Intralum Dev, Open' },
  { text: 'Ultrasonography of Left Wrist, Densitometry' },
  { text: 'Drainage of R Verteb Art with Drain Dev, Open Approach' },
  { text: 'Dilate L Int Iliac Art w Drug-elut Intra, Open' },
  { text: 'Release Right Mandible, Percutaneous Endoscopic Approach' },
  { text: 'Fluoroscopy R Low Extrem Vein w H Osm Contrast, Guidance' },
  { text: 'Removal of Resurfacing Device from L Hip Jt, Open Approach' },
  { text: 'Dilate Abd Aorta, Bifurc, w 2 Drug-elut, Perc Endo' },
  { text: 'Removal of Autol Sub from R Metatarsophal Jt, Perc Approach' },
  { text: 'Revision of Ext Fix in R Wrist Jt, Perc Approach' },
  { text: 'Repair Basal Ganglia, Percutaneous Approach' },
  { text: 'Bypass L Face Vein to Up Vein with Nonaut Sub, Open Approach' },
  { text: 'Supplement L Low Leg Tendon w Synth Sub, Perc Endo' },
  { text: 'Dilate R Thyroid Art, Bifurc, w 4 Drug-elut, Perc' },
  { text: 'Restrict R Basilic Vein w Intralum Dev, Perc Endo' },
  { text: 'Replace of Face Subcu/Fascia with Nonaut Sub, Perc Approach' },
  { text: 'Release Right Rib, Open Approach' },
  { text: 'Dilation of R Pulm Art with Intralum Dev, Perc Approach' },
  { text: 'Inspection of Products of Conception, Open Approach' },
  { text: 'Insertion of Intralum Dev into L Innom Vein, Open Approach' },
  { text: 'Replacement of Left Maxilla with Nonaut Sub, Open Approach' },
  { text: 'Occlusion of Left Ulnar Artery, Perc Endo Approach' },
  { text: 'Occlusion L Up Lobe Bronc w Intralum Dev, Perc' },
  { text: 'Destruction of Right Eye, External Approach' },
  { text: 'Revision of Drainage Device in Coccygeal Jt, Open Approach' },
  { text: 'Restrict R Ext Carotid w Extralum Dev, Perc Endo' },
  { text: 'Dilate R Ext Iliac Art w Drug-elut Intra, Perc Endo' },
  { text: 'Planar Nucl Med Imag of Low Extrem using Thallium 201' },
  { text: 'Insertion of Radioact Elem into GI Tract, Perc Endo Approach' },
  { text: 'Removal of Int Fix from R Glenoid Cav, Perc Endo Approach' },
  { text: 'Drainage of Cul-de-sac with Drain Dev, Perc Endo Approach' },
  { text: 'Excision of Left Vas Deferens, Open Approach' },
  { text: 'Ultrasonography of Bilateral Eyes' },
  { text: 'Replace of L Palatine Bone with Nonaut Sub, Perc Approach' },
  { text: 'Repair Left Humeral Shaft, Percutaneous Endoscopic Approach' },
  { text: 'Insertion of Monitoring Device into Left Lung, Endo' },
  { text: 'Supplement Right Kidney Pelvis with Autol Sub, Endo' },
  { text: 'Drainage of Paraganglion Extremity, Perc Endo Approach' },
  { text: 'Dilate R Thyroid Art, Bifurc, w 3 Drug-elut, Perc Endo' },
  { text: 'Introduction of Anti-inflam into Mouth/Phar, Via Opening' },
  { text: 'Dilation of Right Foot Artery, Bifurcation, Open Approach' },
  { text: 'Extirpation of Matter from Left Scapula, Open Approach' },
  { text: 'Tomo Nucl Med Imag of R & L Heart using Oth Radionuclide' },
  { text: 'Plain Radiography of Left Shoulder' },
  { text: 'Drainage of Left Lower Leg, Perc Endo Approach, Diagn' },
  { text: 'Excision of R Pulm Art, Perc Endo Approach, Diagn' },
  { text: 'Reposition Splenic Artery, Open Approach' },
];
