export const user = [
  {
    firstName: 'Moses',
    lastName: 'Halbert',
    email: 'mhalbert0@barnesandnoble.com',
    password: 'Test@123',
  },
  {
    firstName: 'Idelle',
    lastName: 'Dunnet',
    email: 'idunnet1@earthlink.net',
    password: 'Test@123',
  },
  {
    firstName: 'Say',
    lastName: 'Scrine',
    email: 'sscrine2@geocities.com',
    password: 'Test@123',
  },
  {
    firstName: 'Constantia',
    lastName: 'Drynan',
    email: 'cdrynan3@geocities.com',
    password: 'Test@123',
  },
  {
    firstName: 'Annalee',
    lastName: 'Shugg',
    email: 'ashugg4@imdb.com',
    password: 'Test@123',
  },
  {
    firstName: 'Brinna',
    lastName: 'Gillies',
    email: 'bgillies5@reverbnation.com',
    password: 'Test@123',
  },
  {
    firstName: 'Howie',
    lastName: 'Collumbell',
    email: 'hcollumbell6@unc.edu',
    password: 'Test@123',
  },
  {
    firstName: 'Fidelia',
    lastName: 'Charters',
    email: 'fcharters7@nifty.com',
    password: 'Test@123',
  },
  {
    firstName: 'Michel',
    lastName: 'Birmingham',
    email: 'mbirmingham8@godaddy.com',
    password: 'Test@123',
  },
  {
    firstName: 'Pincas',
    lastName: 'Laible',
    email: 'plaible9@google.cn',
    password: 'Test@123',
  },
  {
    firstName: 'Kareem',
    lastName: 'Brammar',
    email: 'kbrammara@weebly.com',
    password: 'Test@123',
  },
  {
    firstName: 'Marrissa',
    lastName: 'Domerc',
    email: 'mdomercb@state.tx.us',
    password: 'Test@123',
  },
  {
    firstName: 'Kristyn',
    lastName: 'Fulun',
    email: 'kfulunc@google.de',
    password: 'Test@123',
  },
  {
    firstName: 'Todd',
    lastName: 'Dincke',
    email: 'tdincked@delicious.com',
    password: 'Test@123',
  },
  {
    firstName: 'Guido',
    lastName: 'Wombwell',
    email: 'gwombwelle@businesswire.com',
    password: 'Test@123',
  },
  {
    firstName: 'Marline',
    lastName: 'Finlay',
    email: 'mfinlayf@desdev.cn',
    password: 'Test@123',
  },
  {
    firstName: 'Elwyn',
    lastName: 'Stute',
    email: 'estuteg@amazon.co.uk',
    password: 'Test@123',
  },
  {
    firstName: 'Genevieve',
    lastName: 'Tonbye',
    email: 'gtonbyeh@shinystat.com',
    password: 'Test@123',
  },
  {
    firstName: 'Shelley',
    lastName: 'Healings',
    email: 'shealingsi@telegraph.co.uk',
    password: 'Test@123',
  },
  {
    firstName: 'Mayer',
    lastName: 'Maior',
    email: 'mmaiorj@nature.com',
    password: 'Test@123',
  },
  {
    firstName: 'Velvet',
    lastName: 'Tubble',
    email: 'vtubblek@g.co',
    password: 'Test@123',
  },
  {
    firstName: 'Lula',
    lastName: 'Gradley',
    email: 'lgradleyl@wufoo.com',
    password: 'Test@123',
  },
  {
    firstName: 'Cilka',
    lastName: 'Bresnahan',
    email: 'cbresnahanm@utexas.edu',
    password: 'Test@123',
  },
  {
    firstName: 'Merrill',
    lastName: 'Moine',
    email: 'mmoinen@cloudflare.com',
    password: 'Test@123',
  },
  {
    firstName: 'Vitoria',
    lastName: 'Rosoni',
    email: 'vrosonio@simplemachines.org',
    password: 'Test@123',
  },
  {
    firstName: 'Magnum',
    lastName: 'Willows',
    email: 'mwillowsp@networkadvertising.org',
    password: 'Test@123',
  },
  {
    firstName: 'Marie-ann',
    lastName: 'Praill',
    email: 'mpraillq@ameblo.jp',
    password: 'Test@123',
  },
  {
    firstName: 'Josefa',
    lastName: 'Civitillo',
    email: 'jcivitillor@patch.com',
    password: 'Test@123',
  },
  {
    firstName: 'Jaimie',
    lastName: 'Ramsey',
    email: 'jramseys@goo.ne.jp',
    password: 'Test@123',
  },
  {
    firstName: 'Lauretta',
    lastName: 'Joyes',
    email: 'ljoyest@jalbum.net',
    password: 'Test@123',
  },
  {
    firstName: 'Beniamino',
    lastName: 'Corgenvin',
    email: 'bcorgenvinu@instagram.com',
    password: 'Test@123',
  },
  {
    firstName: 'Melisande',
    lastName: 'Savory',
    email: 'msavoryv@umn.edu',
    password: 'Test@123',
  },
  {
    firstName: 'Philis',
    lastName: "O' Connell",
    email: 'poconnellw@nature.com',
    password: 'Test@123',
  },
  {
    firstName: 'Celestyn',
    lastName: 'Souza',
    email: 'csouzax@upenn.edu',
    password: 'Test@123',
  },
  {
    firstName: 'Bank',
    lastName: 'Franschini',
    email: 'bfranschiniy@xinhuanet.com',
    password: 'Test@123',
  },
  {
    firstName: 'Pippy',
    lastName: 'Ealam',
    email: 'pealamz@craigslist.org',
    password: 'Test@123',
  },
  {
    firstName: 'Finn',
    lastName: 'Cullnean',
    email: 'fcullnean10@sciencedaily.com',
    password: 'Test@123',
  },
  {
    firstName: 'Jamesy',
    lastName: 'Martinolli',
    email: 'jmartinolli11@topsy.com',
    password: 'Test@123',
  },
  {
    firstName: 'Dallas',
    lastName: 'Clewer',
    email: 'dclewer12@slashdot.org',
    password: 'Test@123',
  },
  {
    firstName: 'Whit',
    lastName: 'De Simoni',
    email: 'wdesimoni13@networksolutions.com',
    password: 'Test@123',
  },
  {
    firstName: 'Giacobo',
    lastName: 'Yate',
    email: 'gyate14@bloomberg.com',
    password: 'Test@123',
  },
  {
    firstName: 'Langston',
    lastName: 'Leer',
    email: 'lleer15@com.com',
    password: 'Test@123',
  },
  {
    firstName: 'Desirae',
    lastName: 'Coltart',
    email: 'dcoltart16@t.co',
    password: 'Test@123',
  },
  {
    firstName: 'Desiree',
    lastName: 'Pointing',
    email: 'dpointing17@mayoclinic.com',
    password: 'Test@123',
  },
  {
    firstName: 'Francyne',
    lastName: 'Kivelhan',
    email: 'fkivelhan18@deliciousdays.com',
    password: 'Test@123',
  },
  {
    firstName: 'Electra',
    lastName: 'Lile',
    email: 'elile19@businessweek.com',
    password: 'Test@123',
  },
  {
    firstName: 'Dyna',
    lastName: 'Lavens',
    email: 'dlavens1a@arstechnica.com',
    password: 'Test@123',
  },
  {
    firstName: 'Cati',
    lastName: 'Mattielli',
    email: 'cmattielli1b@rakuten.co.jp',
    password: 'Test@123',
  },
  {
    firstName: 'Evonne',
    lastName: 'Senechault',
    email: 'esenechault1c@newyorker.com',
    password: 'Test@123',
  },
  {
    firstName: 'Abby',
    lastName: 'Minerdo',
    email: 'aminerdo1d@alexa.com',
    password: 'Test@123',
  },
  {
    firstName: 'Jackson',
    lastName: 'Stot',
    email: 'jstot1e@sohu.com',
    password: 'Test@123',
  },
  {
    firstName: 'Elton',
    lastName: 'Klulik',
    email: 'eklulik1f@aol.com',
    password: 'Test@123',
  },
  {
    firstName: 'Hilario',
    lastName: 'Emmet',
    email: 'hemmet1g@oaic.gov.au',
    password: 'Test@123',
  },
  {
    firstName: 'Shandeigh',
    lastName: 'Tinghill',
    email: 'stinghill1h@xrea.com',
    password: 'Test@123',
  },
  {
    firstName: 'Munmro',
    lastName: 'Hostan',
    email: 'mhostan1i@ebay.com',
    password: 'Test@123',
  },
  {
    firstName: 'Kennett',
    lastName: 'Medhurst',
    email: 'kmedhurst1j@youku.com',
    password: 'Test@123',
  },
  {
    firstName: 'Leonard',
    lastName: 'Berrigan',
    email: 'lberrigan1k@dedecms.com',
    password: 'Test@123',
  },
  {
    firstName: 'Luciana',
    lastName: 'Skedge',
    email: 'lskedge1l@reuters.com',
    password: 'Test@123',
  },
  {
    firstName: 'Sheridan',
    lastName: 'Knappe',
    email: 'sknappe1m@360.cn',
    password: 'Test@123',
  },
  {
    firstName: 'Saunders',
    lastName: 'Lightbourne',
    email: 'slightbourne1n@mashable.com',
    password: 'Test@123',
  },
  {
    firstName: 'Gretal',
    lastName: 'McCrackan',
    email: 'gmccrackan1o@bing.com',
    password: 'Test@123',
  },
  {
    firstName: 'Waly',
    lastName: 'Kemston',
    email: 'wkemston1p@i2i.jp',
    password: 'Test@123',
  },
  {
    firstName: 'Zsazsa',
    lastName: 'McTeague',
    email: 'zmcteague1q@ibm.com',
    password: 'Test@123',
  },
  {
    firstName: 'Claudian',
    lastName: 'Edgeson',
    email: 'cedgeson1r@netlog.com',
    password: 'Test@123',
  },
  {
    firstName: 'Nicoli',
    lastName: 'Mcimmie',
    email: 'nmcimmie1s@ebay.co.uk',
    password: 'Test@123',
  },
  {
    firstName: 'Mureil',
    lastName: 'Ledwich',
    email: 'mledwich1t@netscape.com',
    password: 'Test@123',
  },
  {
    firstName: 'Travus',
    lastName: 'Iddens',
    email: 'tiddens1u@typepad.com',
    password: 'Test@123',
  },
  {
    firstName: 'Charlean',
    lastName: 'Mcall',
    email: 'cmcall1v@engadget.com',
    password: 'Test@123',
  },
  {
    firstName: 'Bobine',
    lastName: 'Zammitt',
    email: 'bzammitt1w@studiopress.com',
    password: 'Test@123',
  },
  {
    firstName: 'Buddie',
    lastName: 'Weavers',
    email: 'bweavers1x@1688.com',
    password: 'Test@123',
  },
  {
    firstName: 'Rodney',
    lastName: 'Fache',
    email: 'rfache1y@t.co',
    password: 'Test@123',
  },
  {
    firstName: 'Hyman',
    lastName: 'Casin',
    email: 'hcasin1z@jugem.jp',
    password: 'Test@123',
  },
  {
    firstName: 'Wayland',
    lastName: 'Bernli',
    email: 'wbernli20@apple.com',
    password: 'Test@123',
  },
  {
    firstName: 'Leo',
    lastName: 'Gollard',
    email: 'lgollard21@cisco.com',
    password: 'Test@123',
  },
  {
    firstName: 'Cleon',
    lastName: 'Harrowing',
    email: 'charrowing22@mayoclinic.com',
    password: 'Test@123',
  },
  {
    firstName: 'Natala',
    lastName: 'Gatward',
    email: 'ngatward23@delicious.com',
    password: 'Test@123',
  },
  {
    firstName: 'Costa',
    lastName: 'Kenset',
    email: 'ckenset24@furl.net',
    password: 'Test@123',
  },
  {
    firstName: 'Jordan',
    lastName: 'Kinzett',
    email: 'jkinzett25@bloomberg.com',
    password: 'Test@123',
  },
  {
    firstName: 'Phedra',
    lastName: 'Haggleton',
    email: 'phaggleton26@ox.ac.uk',
    password: 'Test@123',
  },
  {
    firstName: 'Felipa',
    lastName: 'Jeness',
    email: 'fjeness27@mapy.cz',
    password: 'Test@123',
  },
  {
    firstName: 'Emmy',
    lastName: 'Warland',
    email: 'ewarland28@miitbeian.gov.cn',
    password: 'Test@123',
  },
  {
    firstName: 'Georgina',
    lastName: 'Casassa',
    email: 'gcasassa29@sun.com',
    password: 'Test@123',
  },
  {
    firstName: 'Harriet',
    lastName: 'Shoreson',
    email: 'hshoreson2a@umn.edu',
    password: 'Test@123',
  },
  {
    firstName: 'Donavon',
    lastName: 'Ferie',
    email: 'dferie2b@blogspot.com',
    password: 'Test@123',
  },
  {
    firstName: 'Ira',
    lastName: 'Ridesdale',
    email: 'iridesdale2c@issuu.com',
    password: 'Test@123',
  },
  {
    firstName: 'Adara',
    lastName: 'Pedley',
    email: 'apedley2d@constantcontact.com',
    password: 'Test@123',
  },
  {
    firstName: 'Willa',
    lastName: 'Johnstone',
    email: 'wjohnstone2e@nydailynews.com',
    password: 'Test@123',
  },
  {
    firstName: 'Cindee',
    lastName: 'Siemantel',
    email: 'csiemantel2f@yale.edu',
    password: 'Test@123',
  },
  {
    firstName: 'Herold',
    lastName: 'Pinhorn',
    email: 'hpinhorn2g@infoseek.co.jp',
    password: 'Test@123',
  },
  {
    firstName: 'Biddie',
    lastName: 'Nugent',
    email: 'bnugent2h@netvibes.com',
    password: 'Test@123',
  },
  {
    firstName: 'Feliks',
    lastName: 'Skypp',
    email: 'fskypp2i@sciencedirect.com',
    password: 'Test@123',
  },
  {
    firstName: 'Kelsey',
    lastName: 'Cheesworth',
    email: 'kcheesworth2j@slideshare.net',
    password: 'Test@123',
  },
  {
    firstName: 'Licha',
    lastName: 'Latty',
    email: 'llatty2k@sciencedirect.com',
    password: 'Test@123',
  },
  {
    firstName: 'Marcela',
    lastName: 'Whatman',
    email: 'mwhatman2l@sfgate.com',
    password: 'Test@123',
  },
  {
    firstName: 'Francklyn',
    lastName: 'Fulop',
    email: 'ffulop2m@army.mil',
    password: 'Test@123',
  },
  {
    firstName: 'Moria',
    lastName: 'Kitman',
    email: 'mkitman2n@trellian.com',
    password: 'Test@123',
  },
  {
    firstName: 'Kelcie',
    lastName: 'Gilstin',
    email: 'kgilstin2o@samsung.com',
    password: 'Test@123',
  },
  {
    firstName: 'Pierette',
    lastName: 'Richings',
    email: 'prichings2p@issuu.com',
    password: 'Test@123',
  },
  {
    firstName: 'Mildrid',
    lastName: 'Tarbert',
    email: 'mtarbert2q@behance.net',
    password: 'Test@123',
  },
  {
    firstName: 'Veradis',
    lastName: 'Adds',
    email: 'vadds2r@bing.com',
    password: 'Test@123',
  },
];
